# Generated by Django 6.0.4 on 2026-05-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentrecord_stripe_checkout_session_id_and_webhook_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentrecord',
            new_name='payment_payment_42bbcf_idx',
            old_name='payments_pa_payment_c92984_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentrecord',
            new_name='payment_status_1c1ab2_idx',
            old_name='payments_pa_status_1764ff_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentrecord',
            new_name='payment_paid_at_a3dd0c_idx',
            old_name='payments_pa_paid_at_9c4fc2_idx',
        ),
        migrations.AlterModelTable(
            name='paymentrecord',
            table='payment',
        ),
    ]
