# Generated by Django 6.0.4 on 2026-07-20 11:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_alter_invoice_status'),
        ('payments', '0007_ensure_manual_customer_notice_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('partially_refunded', 'Partially Refunded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='SGD', max_length=3)),
                ('method', models.CharField(choices=[('stripe', 'Stripe'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('customer_message', models.TextField()),
                ('stripe_refund_id', models.CharField(blank=True, max_length=255)),
                ('bank_reference', models.CharField(blank=True, max_length=100)),
                ('failure_reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_refunds_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_refunds', to='invoicing.invoice')),
                ('payment_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.paymentrecord')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_refunds_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_refund',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payment_ref_status_a5dd15_idx'), models.Index(fields=['method'], name='payment_ref_method_833807_idx'), models.Index(fields=['processed_at'], name='payment_ref_process_59ae06_idx'), models.Index(fields=['stripe_refund_id'], name='payment_ref_stripe__4fd9e5_idx')],
            },
        ),
    ]
