# Generated by Django 6.0.4 on 2026-05-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_action_b32d4d_idx',
            old_name='core_auditl_action_d9fb24_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_created_5a7975_idx',
            old_name='core_auditl_created_dc23ea_idx',
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='audit_log',
        ),
    ]
