# Generated by Django 6.0.4 on 2026-04-27 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.CheckConstraint(condition=models.Q(('total_rows__gte', 0)), name='import_job_total_rows_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.CheckConstraint(condition=models.Q(('valid_rows__gte', 0)), name='import_job_valid_rows_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.CheckConstraint(condition=models.Q(('invalid_rows__gte', 0)), name='import_job_invalid_rows_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.CheckConstraint(condition=models.Q(('saved_rows__gte', 0)), name='import_job_saved_rows_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.CheckConstraint(condition=models.Q(('valid_rows__lte', models.F('total_rows'))), name='import_job_valid_rows_lte_total_rows'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.CheckConstraint(condition=models.Q(('invalid_rows__lte', models.F('total_rows'))), name='import_job_invalid_rows_lte_total_rows'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.CheckConstraint(condition=models.Q(('saved_rows__lte', models.F('valid_rows'))), name='import_job_saved_rows_lte_valid_rows'),
        ),
    ]
