# Generated by Django 6.0.4 on 2026-05-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_importjob_import_job_total_rows_non_negative_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='importjob',
            new_name='import_job_module_a69cf9_idx',
            old_name='imports_imp_module_e7fa39_idx',
        ),
        migrations.RenameIndex(
            model_name='importjob',
            new_name='import_job_status_7cd937_idx',
            old_name='imports_imp_status_b5f1b5_idx',
        ),
        migrations.RenameIndex(
            model_name='importjob',
            new_name='import_job_created_d7bb74_idx',
            old_name='imports_imp_created_2e10b1_idx',
        ),
        migrations.RenameIndex(
            model_name='importrowerror',
            new_name='import_erro_import__962dfc_idx',
            old_name='imports_imp_import__96f841_idx',
        ),
        migrations.AlterModelTable(
            name='importjob',
            table='import_job',
        ),
        migrations.AlterModelTable(
            name='importrowerror',
            table='import_error',
        ),
    ]
