# Generated by Django 6.0.4 on 2026-05-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('superadmin', 'SuperAdmin'), ('admin', 'Admin'), ('finance', 'Finance'), ('hr', 'HR'), ('staff', 'Staff'), ('customer', 'Customer')], default='staff', max_length=20),
        ),
    ]
