# Generated by Django 6.0.4 on 2026-05-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    # This migration runs after superuser roles are backfilled.
    dependencies = [
        ('accounts', '0003_backfill_superadmin_role'),
    ]

    # Update role display labels, such as Finance Officer and Payroll Officer.
    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('superadmin', 'SuperAdmin'), ('admin', 'Admin'), ('finance', 'Finance Officer'), ('hr', 'Payroll Officer'), ('staff', 'Staff'), ('customer', 'Customer')], default='staff', max_length=20),
        ),
    ]
