# Generated by Django 6.0.4 on 2026-05-21 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userrole_code_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userrole',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='suspended_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrole',
            name='suspended_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='LoginSecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'SuperAdmin'), ('admin', 'Admin'), ('finance', 'Finance Officer'), ('hr', 'Payroll Officer'), ('staff', 'Staff'), ('customer', 'Customer')], max_length=20, unique=True)),
                ('max_failed_login_attempts', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_login_security_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role'],
            },
        ),
    ]
