# Generated by Django 6.0.4 on 2026-05-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_emailverificationtoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='accounts_em_token_5f2b37_idx',
            old_name='accounts_ema_token_37ec8f_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='accounts_em_expires_f36bd3_idx',
            old_name='accounts_ema_expires_529fd5_idx',
        ),
    ]
