# Generated by Django 6.0.4 on 2026-06-22 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('invoice', 'Invoice'), ('payment', 'Payment'), ('payroll', 'Payroll'), ('account', 'Account'), ('other', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('related_reference', models.CharField(blank=True, help_text='Optional invoice, payment, or payroll reference.', max_length=100)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_ticket',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='support_tic_categor_1ed42d_idx'), models.Index(fields=['status'], name='support_tic_status_363e60_idx'), models.Index(fields=['priority'], name='support_tic_priorit_a48b90_idx'), models.Index(fields=['created_at'], name='support_tic_created_438cd5_idx')],
            },
        ),
    ]
