# Generated by Django 6.0.4 on 2026-04-30 13:05

import invoicing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_alter_invoiceitem_line_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='public_view_token',
            field=models.CharField(db_index=True, default=invoicing.models.generate_public_view_token, max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['public_view_token'], name='invoicing_i_public__aa0d66_idx'),
        ),
    ]
