# Generated by Django 6.0.4 on 2026-05-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_invoice_public_view_token_invoice_view_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSourceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(blank=True, max_length=50)),
                ('shop_title', models.CharField(blank=True, max_length=255)),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('partner_type_name', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('product_type', models.CharField(blank=True, max_length=100)),
                ('customer_id', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('order_status', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('contact_no', models.CharField(blank=True, max_length=50)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('booked_date', models.DateTimeField(blank=True, null=True)),
                ('service_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=50)),
                ('staff_name', models.CharField(blank=True, max_length=255)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit_card', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('shipping_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reward_point', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vaniday_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vaniday_share', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cashback_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cashback_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cashback_date', models.DateField(blank=True, null=True)),
                ('salon_share', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source_file_name', models.CharField(default='Vaniday Invoice Sample data_RP.csv', max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['order_id'], name='invoicing_i_order_i_4848b4_idx'), models.Index(fields=['email'], name='invoicing_i_email_672006_idx'), models.Index(fields=['booked_date'], name='invoicing_i_booked__a67ea7_idx')],
            },
        ),
    ]
