# Generated by Django 6.0.4 on 2026-05-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_invoicesourcerow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='customer_status_7c387b_idx',
            old_name='invoicing_c_status_35963c_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customer_email_c21aac_idx',
            old_name='invoicing_c_email_f65b6a_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoice_invoice_5b7137_idx',
            old_name='invoicing_i_invoice_f2b05e_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoice_status_25ea8f_idx',
            old_name='invoicing_i_status_2eeee5_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoice_issue_d_7c8de8_idx',
            old_name='invoicing_i_issue_d_436aef_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoice_due_dat_ee8b9c_idx',
            old_name='invoicing_i_due_dat_92e42f_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoice_public__5a83d9_idx',
            old_name='invoicing_i_public__aa0d66_idx',
        ),
        migrations.RenameIndex(
            model_name='invoiceitem',
            new_name='invoice_ite_invoice_74f52f_idx',
            old_name='invoicing_i_invoice_0b11e7_idx',
        ),
        migrations.RenameIndex(
            model_name='invoicesourcerow',
            new_name='invoice_sou_order_i_ccae4f_idx',
            old_name='invoicing_i_order_i_4848b4_idx',
        ),
        migrations.RenameIndex(
            model_name='invoicesourcerow',
            new_name='invoice_sou_email_f2b9b6_idx',
            old_name='invoicing_i_email_672006_idx',
        ),
        migrations.RenameIndex(
            model_name='invoicesourcerow',
            new_name='invoice_sou_booked__79e8a5_idx',
            old_name='invoicing_i_booked__a67ea7_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Pending Payment'), ('viewed', 'Viewed'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', max_length=20),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='invoice',
        ),
        migrations.AlterModelTable(
            name='invoiceitem',
            table='invoice_item',
        ),
        migrations.AlterModelTable(
            name='invoicesourcerow',
            table='invoice_source_row',
        ),
    ]
