# Generated by Django 6.0.4 on 2026-05-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0005_rename_invoicing_c_status_35963c_idx_customer_status_7c387b_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Pending Payment"),
                    ("viewed", "Viewed"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("refunded", "Refunded"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
