# Generated by Django 6.0.4 on 2026-07-07 14:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_or_repair_invoice_template_settings_table(apps, schema_editor):
    table_name = "invoice_template_settings"
    index_name = f"{table_name}_updated_by_id_idx"
    constraint_name = f"{table_name}_updated_by_fk"
    existing_tables = set(schema_editor.connection.introspection.table_names())
    user_table = "user" if "user" in existing_tables else "auth_user"
    vendor = schema_editor.connection.vendor

    if vendor == "mysql":
        if table_name not in existing_tables:
            schema_editor.execute(
                f"""
                CREATE TABLE `{table_name}` (
                    `id` bigint NOT NULL AUTO_INCREMENT,
                    `company_display_name` varchar(255) NOT NULL DEFAULT '',
                    `company_address` longtext NOT NULL,
                    `logo` varchar(100) NOT NULL DEFAULT '',
                    `logo_size` varchar(10) NOT NULL DEFAULT 'medium',
                    `logo_position` varchar(10) NOT NULL DEFAULT 'left',
                    `address_position` varchar(10) NOT NULL DEFAULT 'left',
                    `updated_at` datetime(6) NOT NULL,
                    `updated_by_id` int NULL,
                    PRIMARY KEY (`id`),
                    KEY `{index_name}` (`updated_by_id`),
                    CONSTRAINT `{constraint_name}`
                        FOREIGN KEY (`updated_by_id`) REFERENCES `{user_table}` (`id`)
                );
                """
            )
            return

        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT COUNT(*)
                FROM information_schema.statistics
                WHERE table_schema = DATABASE()
                  AND table_name = %s
                  AND index_name = %s
                """,
                [table_name, index_name],
            )
            has_index = bool(cursor.fetchone()[0])
            cursor.execute(
                """
                SELECT COUNT(*)
                FROM information_schema.table_constraints
                WHERE table_schema = DATABASE()
                  AND table_name = %s
                  AND constraint_name = %s
                  AND constraint_type = 'FOREIGN KEY'
                """,
                [table_name, constraint_name],
            )
            has_constraint = bool(cursor.fetchone()[0])

        if not has_index:
            schema_editor.execute(
                f"ALTER TABLE `{table_name}` ADD INDEX `{index_name}` (`updated_by_id`);"
            )
        if not has_constraint:
            schema_editor.execute(
                f"""
                ALTER TABLE `{table_name}`
                ADD CONSTRAINT `{constraint_name}`
                    FOREIGN KEY (`updated_by_id`) REFERENCES `{user_table}` (`id`);
                """
            )
        return

    if table_name in existing_tables:
        return

    schema_editor.execute(
        f"""
        CREATE TABLE "{table_name}" (
            "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
            "company_display_name" varchar(255) NOT NULL DEFAULT '',
            "company_address" text NOT NULL,
            "logo" varchar(100) NOT NULL DEFAULT '',
            "logo_size" varchar(10) NOT NULL DEFAULT 'medium',
            "logo_position" varchar(10) NOT NULL DEFAULT 'left',
            "address_position" varchar(10) NOT NULL DEFAULT 'left',
            "updated_at" datetime NOT NULL,
            "updated_by_id" integer NULL
                REFERENCES "{user_table}" ("id") DEFERRABLE INITIALLY DEFERRED
        );
        """
    )
    schema_editor.execute(
        f'CREATE INDEX "{index_name}" ON "{table_name}" ("updated_by_id");'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_invoice_refunded_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_or_repair_invoice_template_settings_table,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='InvoiceTemplateSettings',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('company_display_name', models.CharField(blank=True, default='', max_length=255)),
                        ('company_address', models.TextField(blank=True, default='')),
                        ('logo', models.ImageField(blank=True, default='', upload_to='invoice_branding/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                        ('logo_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                        ('logo_position', models.CharField(choices=[('left', 'Left'), ('centre', 'Centre'), ('right', 'Right')], default='left', max_length=10)),
                        ('address_position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=10)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_template_settings_updates', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Invoice template settings',
                        'verbose_name_plural': 'Invoice template settings',
                        'db_table': 'invoice_template_settings',
                    },
                ),
            ],
        ),
    ]
