# Generated by Django 6.0.4 on 2026-07-15 05:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_invoicetemplatesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetemplatesettings',
            name='company_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='invoicetemplatesettings',
            name='company_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invoicetemplatesettings',
            name='company_registration_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoicetemplatesettings',
            name='default_payment_term_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='invoicetemplatesettings',
            name='footer_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoicetemplatesettings',
            name='header_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoicetemplatesettings',
            name='invoice_payment_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoicetemplatesettings',
            name='registered_office_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
