# Generated by Django 6.0.4 on 2026-07-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_invoicetemplatesettings_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Pending Payment'), ('viewed', 'Viewed'), ('paid', 'Paid'), ('partially_refunded', 'Partially Refunded'), ('overdue', 'Overdue'), ('refunded', 'Refunded')], default='draft', max_length=20),
        ),
    ]
