# Generated by Django 6.0.4 on 2026-05-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_align_payroll_table_names'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employee',
            new_name='employee_employe_3e3e4c_idx',
            old_name='payroll_emp_employe_b2acf6_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='employee_status_d74ea5_idx',
            old_name='payroll_emp_status_98fdd7_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='employee_email_c0d4f7_idx',
            old_name='payroll_emp_email_65306c_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollbatch',
            new_name='payroll_det_batch_r_b78e2a_idx',
            old_name='payroll_pay_batch_r_35cad5_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollbatch',
            new_name='payroll_det_status_7f7355_idx',
            old_name='payroll_pay_status_263673_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollbatch',
            new_name='payroll_det_payout__e6319d_idx',
            old_name='payroll_pay_payout__6302d8_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollentry',
            new_name='payroll_status_ac0f6a_idx',
            old_name='payroll_pay_status_adfd17_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollentry',
            new_name='payroll_batch_i_78bcf4_idx',
            old_name='payroll_pay_batch_i_b6f59d_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollrecord',
            new_name='payslip_rec_payment_d6c922_idx',
            old_name='payroll_rec_payment_f25508_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollrecord',
            new_name='payslip_rec_employe_aec5f1_idx',
            old_name='payroll_rec_employe_13cd41_idx',
        ),
        migrations.RenameIndex(
            model_name='paysliprecord',
            new_name='legacy_pays_payslip_61e976_idx',
            old_name='payroll_pay_payslip_ad71a8_idx',
        ),
        migrations.RenameIndex(
            model_name='paysliprecord',
            new_name='legacy_pays_status_557570_idx',
            old_name='payroll_pay_status_c38e3d_idx',
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='cpf_exempted',
            field=models.BooleanField(blank=True, db_column='cpf_exempted', null=True),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='nric',
            field=models.CharField(blank=True, db_column='NRIC', max_length=9),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='sdl_exempted',
            field=models.BooleanField(blank=True, db_column='sdl_exempted', null=True),
        ),
    ]
