# Generated by Django 6.0.4 on 2026-06-16 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_alter_employee_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payrollrecord',
            constraint=models.UniqueConstraint(fields=('employee_id', 'payment_date'), name='unique_payroll_employee_payment_date'),
        ),
    ]
