# Generated by Django 6.0.4 on 2026-07-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_rename_payroll_set_payment_33a5a8_idx_payroll_set_payment_a11092_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_status',
            field=models.CharField(choices=[('none', 'Available'), ('on_leave', 'On Leave')], default='none', max_length=20),
        ),
    ]
