# Generated by Django 6.0.4 on 2026-05-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_paymentremindersettings'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emaildeliverylog',
            new_name='email_log_status_c4fb3b_idx',
            old_name='notificatio_status_ed0b56_idx',
        ),
        migrations.RenameIndex(
            model_name='emaildeliverylog',
            new_name='email_log_recipie_0d21e5_idx',
            old_name='notificatio_recipie_942121_idx',
        ),
        migrations.RenameIndex(
            model_name='emaildeliverylog',
            new_name='email_log_attempt_04f712_idx',
            old_name='notificatio_attempt_b87283_idx',
        ),
        migrations.AlterModelTable(
            name='emaildeliverylog',
            table='email_log',
        ),
    ]
