# Generated by Django 6.0.4 on 2026-05-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_rename_notificatio_status_ed0b56_idx_email_log_status_c4fb3b_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentremindersettings",
            name="after_due_days",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="paymentremindersettings",
            name="after_due_reminders_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paymentremindersettings",
            name="before_due_reminders_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paymentremindersettings",
            name="due_date_reminders_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paymentremindersettings",
            name="overdue_repeat_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
