# Generated by Django 6.0.4 on 2026-07-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_paymentremindersettings_reminder_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentremindersettings',
            name='reminder_body_template',
            field=models.TextField(blank=True, default='Dear {{ customer_name }},\n\nThis is a payment reminder for invoice {{ invoice_number }}.\nDue date: {{ due_date }}\nAmount due: {{ currency }} {{ amount_due }}\n\nView invoice: {{ invoice_link }}\n\nIf payment has already been made, please disregard this reminder.\n\n{{ company_name }}\n{{ company_email }}'),
        ),
        migrations.AddField(
            model_name='paymentremindersettings',
            name='reminder_subject_template',
            field=models.CharField(blank=True, default='Payment Reminder: {{ invoice_number }} is {{ reminder_status }}', max_length=255),
        ),
    ]
